pipeline {
    agent any 

    stages {
        stage('Build') {
            steps {
                sh 'g++ hello.cpp -o hello.out'  // Compile C++ file
            }
        }
        stage('Test') {
            steps {
                sh './hello.out'  // Run the compiled C++ file
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying application...'
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed'
        }
    }
}
